"""Initial schema

Revision ID: 001
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_name', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('replies', sa.Integer(), nullable=True),
    sa.Column('contributors', sa.Integer(), nullable=True),
    sa.Column('search_volume', sa.Integer(), nullable=True),
    sa.Column('like_to_view_ratio', sa.Float(), nullable=True),
    sa.Column('comment_to_view_ratio', sa.Float(), nullable=True),
    sa.Column('popularity_score', sa.Float(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_platform_country', 'workflows', ['platform', 'country'], unique=False)
    op.create_index('idx_score_platform', 'workflows', ['popularity_score', 'platform'], unique=False)
    op.create_index(op.f('ix_workflows_country'), 'workflows', ['country'], unique=False)
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_index(op.f('ix_workflows_platform'), 'workflows', ['platform'], unique=False)
    op.create_index(op.f('ix_workflows_popularity_score'), 'workflows', ['popularity_score'], unique=False)
    op.create_index(op.f('ix_workflows_workflow_name'), 'workflows', ['workflow_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflows_workflow_name'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_popularity_score'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_platform'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_country'), table_name='workflows')
    op.drop_index('idx_score_platform', table_name='workflows')
    op.drop_index('idx_platform_country', table_name='workflows')
    op.drop_table('workflows')
    # ### end Alembic commands ###